version: '3.8'

services:
  sqlserver:
    # voor Microsoft gebaseerde platforms: mcr.microsoft.com/mssql/server:2022-latest
    # Voor Apple gebaseerde platforms: mcr.microsoft.com/azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Blaziken123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: