version: '3.8'

services:
  sqlserver:
#    Aanpassen naar mcr.microsoft.com/mssql/server:2022-latest voor windows gebruikers
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Blaziken123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: